"""
.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
"""
from utils import FileIO as iO
from utils import string_ops as so
from tachyon import quantum as qt


def main():
    lines = iO.parse('input.txt', {'separator': '\n'})
    items = qt.first_beam(so.to_array(lines))
    count = qt.beamify(items)
    
    return count


if __name__ == '__main__':
    print(main())